// import { Inter } from "next/font/google";
// import "./globals.css";

import "./theme.css";

import 'bootstrap/dist/css/bootstrap.min.css';
import 'bootstrap-icons/font/bootstrap-icons.css';

// import "bootstrap/dist/js/bootstrap.bundle.min.js";


// import '../../public/assets/css/core.css';
// import '../../public/assets/css/theme-default.css';


// const inter = Inter({ subsets: ["latin"] });
// import { useEffect } from "react"; // ✅ Import useEffect

export const metadata = {
  title: "Imanage Web App",
  description: "Generated by Intenics Private Limited",
};

   

export default function RootLayout({ children }) {

    return (
        <html lang="en">
            {/* <body className={inter.className}> */}
            <body >
                {children}
            </body>
        </html>
    );
}
